;;; carbon-now-sh-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from carbon-now-sh.el

(autoload 'carbon-now-sh "carbon-now-sh" "\
Open current region in carbon.now.sh." t)
(register-definition-prefixes "carbon-now-sh" '("carbon-now-sh-baseurl"))

;;; End of scraped data

(provide 'carbon-now-sh-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; carbon-now-sh-autoloads.el ends here
