;;; ack-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ack.el

(autoload 'ack "ack" "\
Run ack using COMMAND-ARGS and collect output in a buffer.
When called interactively, the value of DIRECTORY is provided by
`ack-default-directory-function'.

The following keys are available while reading from the
minibuffer:

\\{ack-minibuffer-local-map}

(fn COMMAND-ARGS &optional DIRECTORY)" t)
(register-definition-prefixes "ack" '("ack-"))


;;; Generated autoloads from pcmpl-ack.el

(autoload 'pcomplete/ack "pcmpl-ack" "\
Completion for the `ack' command.
Start an argument with '-' to complete short options and '--' for
long options.")
(defalias 'pcomplete/ack-grep 'pcomplete/ack)
(autoload 'pcomplete/ag "pcmpl-ack" "\
Completion for the `ag' command.")
(register-definition-prefixes "pcmpl-ack" '("pcmpl-ack-"))

;;; End of scraped data

(provide 'ack-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ack-autoloads.el ends here
