blank_issues_enabled: false
contact_links:
  - name: "Jump to github discussions for help"
    url: https://github.com/emacs-helm/helm/discussions
    about: Please search, ask and answer questions here.
