;;; sublimity-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from sublimity.el

(defvar sublimity-mode nil "\
Non-nil if Sublimity mode is enabled.
See the `sublimity-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `sublimity-mode'.")
(custom-autoload 'sublimity-mode "sublimity" nil)
(autoload 'sublimity-mode "sublimity" "\
smooth-scrolling and minimap, like sublime editor

This is a global minor mode.  If called interactively, toggle the
`Sublimity mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='sublimity-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "sublimity" '("sublimity-"))


;;; Generated autoloads from sublimity-attractive.el

(register-definition-prefixes "sublimity-attractive" '("split-window" "sublimity-attractive-"))


;;; Generated autoloads from sublimity-map.el

(register-definition-prefixes "sublimity-map" '("sublimity-map-"))


;;; Generated autoloads from sublimity-scroll.el

(register-definition-prefixes "sublimity-scroll" '("sublimity-scroll-"))


;;; End of scraped data

(provide 'sublimity-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; sublimity-autoloads.el ends here
