;;; helm-project-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-project.el

(autoload 'helm-project-list-projects "helm-project" "\
`helm' for working with known projects.

Also see `helm-project'." t)
(autoload 'helm-project-files "helm-project" "\
`helm' for working with project files.

Also see `helm-project'." t)
(autoload 'helm-project-buffers "helm-project" "\
`helm' for working with project buffers.

Also see `helm-project'." t)
(autoload 'helm-project "helm-project" "\
`helm' for working with projects." t)
(register-definition-prefixes "helm-project" '("helm-project-"))

;;; End of scraped data

(provide 'helm-project-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-project-autoloads.el ends here
