esphome:
  name: esp32-madoka
  friendly_name: esp32-madoka

api:

ota:
  platform: esphome

network:

bluetooth_proxy:

wifi:
  networks:
    - ssid: !secret wifi_ssid
      hidden: true
      password: !secret wifi_password

external_components:
  - source: github://ereslibre/madoka-esphome@madoka
    components: [ madoka ]

esp32:
  board: esp32dev

esp32_ble_tracker:

esp32_ble:
  io_capability: display_yes_no

ble_client:
  - mac_address: "1C:41:90:50:AC:89"
    id: madoka_climate

climate:
  - platform: madoka
    name: "Madoka Climate"
    ble_client_id: madoka_climate
    update_interval: 15s
